// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL7UAwuKyv0tAbtjm1vsU7RJqYDDVhGWk',
    appId: '1:664856122967:web:8edab679fdbb1592943512',
    messagingSenderId: '664856122967',
    projectId: 'sign-up-validation-b34a3',
    authDomain: 'sign-up-validation-b34a3.firebaseapp.com',
    storageBucket: 'sign-up-validation-b34a3.firebasestorage.app',
    measurementId: 'G-BFJVYJRQ5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8sAc--ZR-q7O1Rj2YYZCM7sHVgE41-yM',
    appId: '1:664856122967:android:09cd395cb727d237943512',
    messagingSenderId: '664856122967',
    projectId: 'sign-up-validation-b34a3',
    storageBucket: 'sign-up-validation-b34a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhRcVYjbXGTfn-YX5yY3PCDUqK0Xu0s6k',
    appId: '1:664856122967:ios:09faa86b86267e46943512',
    messagingSenderId: '664856122967',
    projectId: 'sign-up-validation-b34a3',
    storageBucket: 'sign-up-validation-b34a3.firebasestorage.app',
    iosBundleId: 'com.example.skindiseasedetector',
  );
}
